"""Serve the WebGPU SAM 3D page over Gradio's public share tunnel.

Why this exists: on SageMaker Studio, reaching a raw Flask port from the browser
needs jupyter-server-proxy (often missing) and a secure (https) context for
WebGPU. Gradio's `share=True` tunnel already gives a public **https** URL that
works in this environment (you've used it). This launcher piggybacks on that
tunnel: it starts a tiny Gradio app (just to get the tunnel + FastAPI server),
then attaches two raw routes to that same server:

    GET  /app       -> serves web/index.html (full page, scripts intact —
                       gr.HTML would strip them)
    POST /generate  -> proxies to the SageMaker endpoint (boto3, from app.py)

Both are reachable through the share tunnel, so the browser loads the WebGPU
page over https (secure context => WebGPU works) with no Jupyter proxy and no
local AWS creds.

Run:
    export AWS_REGION=us-east-1
    export SAM3D_ENDPOINT=sam3d-objects-g6e
    pip install gradio boto3
    python webapp_gradio.py
Then open the printed  https://....gradio.live/app  URL.
"""

import os

import gradio as gr
from starlette.concurrency import run_in_threadpool
from starlette.responses import HTMLResponse, JSONResponse
from starlette.routing import Route

from app import _default_invoke_factory

# index.html is embedded below (base64) so this file is fully self-contained —
# no separate web/ folder needs to be uploaded.
_INDEX_HTML_B64 = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9IlVURi04IiAvPgo8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMCIgLz4KPHRpdGxlPlNBTSAzRCBPYmplY3RzIOKAlCBXZWJHUFU8L3RpdGxlPgo8c3R5bGU+CiAgOnJvb3QgeyBjb2xvci1zY2hlbWU6IGRhcms7IH0KICBib2R5IHsgbWFyZ2luOiAwOyBmb250LWZhbWlseTogc3lzdGVtLXVpLCBzYW5zLXNlcmlmOyBiYWNrZ3JvdW5kOiAjMGIwYjBmOyBjb2xvcjogI2VhZWFmMDsgfQogIGhlYWRlciB7IHBhZGRpbmc6IDEycHggMThweDsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkICMyMzIzMmI7IH0KICBoZWFkZXIgaDEgeyBmb250LXNpemU6IDE2cHg7IG1hcmdpbjogMDsgZm9udC13ZWlnaHQ6IDYwMDsgfQogIGhlYWRlciBwIHsgbWFyZ2luOiA0cHggMCAwOyBmb250LXNpemU6IDEycHg7IGNvbG9yOiAjOWE5YWE4OyB9CiAgLndyYXAgeyBkaXNwbGF5OiBmbGV4OyBnYXA6IDE2cHg7IHBhZGRpbmc6IDE2cHg7IGZsZXgtd3JhcDogd3JhcDsgfQogIC5jb2wgeyBmbGV4OiAxIDEgNDQwcHg7IG1pbi13aWR0aDogMzYwcHg7IH0KICAucGFuZWwgeyBiYWNrZ3JvdW5kOiAjMTQxNDFiOyBib3JkZXI6IDFweCBzb2xpZCAjMjMyMzJiOyBib3JkZXItcmFkaXVzOiAxMHB4OyBwYWRkaW5nOiAxMnB4OyB9CiAgY2FudmFzI2ltZyB7IG1heC13aWR0aDogMTAwJTsgY3Vyc29yOiBjcm9zc2hhaXI7IGJvcmRlci1yYWRpdXM6IDhweDsgZGlzcGxheTogYmxvY2s7IH0KICAjdmlld2VyIHsgd2lkdGg6IDEwMCU7IGhlaWdodDogNDYwcHg7IGJhY2tncm91bmQ6ICMwZDBkMTI7IGJvcmRlci1yYWRpdXM6IDhweDsgcG9zaXRpb246IHJlbGF0aXZlOyBvdmVyZmxvdzogaGlkZGVuOyB9CiAgLnJvdyB7IGRpc3BsYXk6IGZsZXg7IGdhcDogOHB4OyBhbGlnbi1pdGVtczogY2VudGVyOyBmbGV4LXdyYXA6IHdyYXA7IG1hcmdpbi10b3A6IDEwcHg7IH0KICBidXR0b24geyBiYWNrZ3JvdW5kOiAjMmEyYTM2OyBjb2xvcjogI2VhZWFmMDsgYm9yZGVyOiAxcHggc29saWQgIzNhM2E0ODsgYm9yZGVyLXJhZGl1czogOHB4OyBwYWRkaW5nOiA4cHggMTJweDsgY3Vyc29yOiBwb2ludGVyOyBmb250LXNpemU6IDEzcHg7IH0KICBidXR0b24ucHJpbWFyeSB7IGJhY2tncm91bmQ6ICNlODU5MGM7IGJvcmRlci1jb2xvcjogI2U4NTkwYzsgZm9udC13ZWlnaHQ6IDYwMDsgfQogIGJ1dHRvbjpkaXNhYmxlZCB7IG9wYWNpdHk6IC41OyBjdXJzb3I6IG5vdC1hbGxvd2VkOyB9CiAgbGFiZWwudG9nIHsgZm9udC1zaXplOiAxM3B4OyBkaXNwbGF5OiBpbmxpbmUtZmxleDsgZ2FwOiA1cHg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IH0KICAjc3RhdHVzIHsgZm9udC1zaXplOiAxMnB4OyBjb2xvcjogIzlhOWFhODsgbWFyZ2luLXRvcDogOHB4OyBtaW4taGVpZ2h0OiAxNnB4OyB3aGl0ZS1zcGFjZTogcHJlLXdyYXA7IH0KICBpbnB1dFt0eXBlPXJhbmdlXSB7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7IH0KICBhIHsgY29sb3I6ICNmZmE5NGQ7IH0KPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KPGhlYWRlcj4KICA8aDE+U0FNIDNEIE9iamVjdHMg4oCUIGNsaWNrIGFuIG9iamVjdCwgZ2V0IGEgM0QgbW9kZWwgKFdlYkdQVSk8L2gxPgogIDxwPlNlZ21lbnRhdGlvbiBydW5zIGluIHlvdXIgYnJvd3NlciBvbiB0aGUgR1BVICh0cmFuc2Zvcm1lcnMuanMgKyBXZWJHUFUpLiBUaGUgM0QgbGlmdCBydW5zIG9uIHRoZSBTYWdlTWFrZXIgZW5kcG9pbnQuIENsaWNrIHRoZSBvYmplY3QsIHJlZmluZSB3aXRoIG1vcmUgY2xpY2tzLCB0aGVuIEdlbmVyYXRlIDNEIGFuZCBkcmFnIHRvIHJvdGF0ZS48L3A+CjwvaGVhZGVyPgoKPGRpdiBjbGFzcz0id3JhcCI+CiAgPGRpdiBjbGFzcz0iY29sIHBhbmVsIj4KICAgIDxkaXYgY2xhc3M9InJvdyI+CiAgICAgIDxpbnB1dCB0eXBlPSJmaWxlIiBpZD0iZmlsZSIgYWNjZXB0PSJpbWFnZS8qIiAvPgogICAgICA8YnV0dG9uIGlkPSJ1c2VTYW1wbGUiPlVzZSBzYW1wbGUgaW1hZ2U8L2J1dHRvbj4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icm93Ij4KICAgICAgPGNhbnZhcyBpZD0iaW1nIj48L2NhbnZhcz4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icm93Ij4KICAgICAgPGxhYmVsIGNsYXNzPSJ0b2ciPjxpbnB1dCB0eXBlPSJyYWRpbyIgbmFtZT0ibW9kZSIgdmFsdWU9IjEiIGNoZWNrZWQgLz4gQWRkIChmb3JlZ3JvdW5kKTwvbGFiZWw+CiAgICAgIDxsYWJlbCBjbGFzcz0idG9nIj48aW5wdXQgdHlwZT0icmFkaW8iIG5hbWU9Im1vZGUiIHZhbHVlPSIwIiAvPiBSZW1vdmUgKGJhY2tncm91bmQpPC9sYWJlbD4KICAgIDwvZGl2PgogICAgPGRpdiBjbGFzcz0icm93Ij4KICAgICAgPGJ1dHRvbiBpZD0iY2xlYXIiPkNsZWFyIHBvaW50czwvYnV0dG9uPgogICAgICA8YnV0dG9uIGlkPSJnZW4iIGNsYXNzPSJwcmltYXJ5IiBkaXNhYmxlZD5HZW5lcmF0ZSAzRDwvYnV0dG9uPgogICAgICA8bGFiZWwgY2xhc3M9InRvZyI+U2VlZCA8aW5wdXQgdHlwZT0ibnVtYmVyIiBpZD0ic2VlZCIgdmFsdWU9IjQyIiBtaW49IjAiIG1heD0iOTk5OSIgc3R5bGU9IndpZHRoOjY0cHgiIC8+PC9sYWJlbD4KICAgIDwvZGl2PgogICAgPGRpdiBpZD0ic3RhdHVzIj5Mb2FkaW5nIFNBTSAoV2ViR1BVKeKApjwvZGl2PgogIDwvZGl2PgoKICA8ZGl2IGNsYXNzPSJjb2wgcGFuZWwiPgogICAgPGRpdiBpZD0idmlld2VyIj48L2Rpdj4KICAgIDxkaXYgaWQ9InN0YXR1czNkIiBzdHlsZT0iZm9udC1zaXplOjEycHg7Y29sb3I6IzlhOWFhODttYXJnaW4tdG9wOjhweDsiPlRoZSAzRCByZXN1bHQgYXBwZWFycyBoZXJlIOKAlCBkcmFnIHRvIHJvdGF0ZSwgc2Nyb2xsIHRvIHpvb20uPC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJyb3ciPjxhIGlkPSJkbCIgc3R5bGU9ImRpc3BsYXk6bm9uZSI+RG93bmxvYWQgLnBseTwvYT48L2Rpdj4KICA8L2Rpdj4KPC9kaXY+Cgo8c2NyaXB0IHR5cGU9Im1vZHVsZSI+CmltcG9ydCB7CiAgU2FtTW9kZWwsIEF1dG9Qcm9jZXNzb3IsIFJhd0ltYWdlLCBUZW5zb3IsIGVudgp9IGZyb20gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGh1Z2dpbmdmYWNlL3RyYW5zZm9ybWVyc0A0LjIuMCc7Cgpjb25zdCBTQU1QTEVfVVJMID0gJ2h0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9mYWNlYm9va3Jlc2VhcmNoL3NhbS0zZC1vYmplY3RzL21haW4vbm90ZWJvb2svaW1hZ2VzL3NodXR0ZXJzdG9ja19zdHlsaXNoX2tpZHNyb29tXzE2NDA4MDY1NjcvaW1hZ2UucG5nJzsKY29uc3QgTU9ERUxfSUQgPSAnWGVub3ZhL3NsaW1zYW0tNzctdW5pZm9ybSc7Cgpjb25zdCBzdGF0dXNFbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzdGF0dXMnKTsKY29uc3Qgc3RhdHVzM2RFbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzdGF0dXMzZCcpOwpjb25zdCBjYW52YXMgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnaW1nJyk7CmNvbnN0IGN0eCA9IGNhbnZhcy5nZXRDb250ZXh0KCcyZCcpOwpjb25zdCBnZW5CdG4gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZ2VuJyk7CgpsZXQgbW9kZWwsIHByb2Nlc3NvcjsKbGV0IGltYWdlUmF3ID0gbnVsbDsgICAgICAgIC8vIFJhd0ltYWdlIG9mIHRoZSBjdXJyZW50IGltYWdlCmxldCBpbWFnZUlucHV0cyA9IG51bGw7ICAgICAvLyBwcm9jZXNzb3Igb3V0cHV0cyAocmVzaGFwZWQvb3JpZ2luYWwgc2l6ZXMpCmxldCBpbWFnZUVtYmVkZGluZ3MgPSBudWxsOyAvLyBjYWNoZWQgU0FNIGVtYmVkZGluZyBmb3IgdGhlIGN1cnJlbnQgaW1hZ2UKbGV0IGNsaWNrcyA9IFtdOyAgICAgICAgICAgIC8vIFt7eCx5LGxhYmVsfV0gaW4gZGlzcGxheWVkLWNhbnZhcyBwaXhlbCBjb29yZHMgKD0gbmF0dXJhbCBweCkKbGV0IGxhc3RNYXNrID0gbnVsbDsgICAgICAgIC8vIHtkYXRhOiBVaW50OCwgd2lkdGgsIGhlaWdodH0gYmVzdCBtYXNrIGF0IG9yaWdpbmFsIHNpemUKCmZ1bmN0aW9uIHNldFN0YXR1cyhzKSB7IHN0YXR1c0VsLnRleHRDb250ZW50ID0gczsgfQoKLy8gLS0tLSBsb2FkIFNBTSAoV2ViR1BVLCBmcDE2OyBmYWxscyBiYWNrIHRvIHdhc20gaWYgV2ViR1BVIGlzIHVuYXZhaWxhYmxlKSAtLS0tCihhc3luYyAoKSA9PiB7CiAgY29uc3QgaGFzV2ViR1BVID0gJ2dwdScgaW4gbmF2aWdhdG9yOwogIGNvbnN0IGRldmljZSA9IGhhc1dlYkdQVSA/ICd3ZWJncHUnIDogJ3dhc20nOwogIGNvbnN0IGR0eXBlID0gaGFzV2ViR1BVID8gJ2ZwMTYnIDogJ3E4JzsKICB0cnkgewogICAgbW9kZWwgPSBhd2FpdCBTYW1Nb2RlbC5mcm9tX3ByZXRyYWluZWQoTU9ERUxfSUQsIHsgZHR5cGUsIGRldmljZSB9KTsKICAgIHByb2Nlc3NvciA9IGF3YWl0IEF1dG9Qcm9jZXNzb3IuZnJvbV9wcmV0cmFpbmVkKE1PREVMX0lEKTsKICAgIHNldFN0YXR1cyhgU0FNIHJlYWR5IG9uICR7ZGV2aWNlLnRvVXBwZXJDYXNlKCl9LiBMb2FkIGFuIGltYWdlIChvciB1c2UgdGhlIHNhbXBsZSkgYW5kIGNsaWNrIHRoZSBvYmplY3QuYCk7CiAgfSBjYXRjaCAoZSkgewogICAgc2V0U3RhdHVzKCdGYWlsZWQgdG8gbG9hZCBTQU06ICcgKyBlKTsKICAgIHRocm93IGU7CiAgfQp9KSgpOwoKLy8gLS0tLSBpbWFnZSBsb2FkaW5nIC0tLS0KYXN5bmMgZnVuY3Rpb24gbG9hZEltYWdlRnJvbVVSTCh1cmwpIHsKICBzZXRTdGF0dXMoJ0VuY29kaW5nIGltYWdlIChvbmUtdGltZSBwZXIgaW1hZ2Up4oCmJyk7CiAgaW1hZ2VSYXcgPSBhd2FpdCBSYXdJbWFnZS5yZWFkKHVybCk7CiAgLy8gRHJhdyBhdCBuYXR1cmFsIHNpemUgaW50byB0aGUgY2FudmFzLgogIGNhbnZhcy53aWR0aCA9IGltYWdlUmF3LndpZHRoOwogIGNhbnZhcy5oZWlnaHQgPSBpbWFnZVJhdy5oZWlnaHQ7CiAgY29uc3QgY2ltZyA9IGltYWdlUmF3LnRvQ2FudmFzID8gaW1hZ2VSYXcudG9DYW52YXMoKSA6IG51bGw7CiAgaWYgKGNpbWcpIGN0eC5kcmF3SW1hZ2UoY2ltZywgMCwgMCk7CiAgZWxzZSB7CiAgICBjb25zdCBpbSA9IG5ldyBJbWFnZSgpOyBpbS5zcmMgPSB1cmw7CiAgICBhd2FpdCBpbS5kZWNvZGUoKTsgY3R4LmRyYXdJbWFnZShpbSwgMCwgMCwgY2FudmFzLndpZHRoLCBjYW52YXMuaGVpZ2h0KTsKICB9CiAgY2xpY2tzID0gW107IGxhc3RNYXNrID0gbnVsbDsgZ2VuQnRuLmRpc2FibGVkID0gdHJ1ZTsKICBpbWFnZUlucHV0cyA9IGF3YWl0IHByb2Nlc3NvcihpbWFnZVJhdyk7CiAgaW1hZ2VFbWJlZGRpbmdzID0gYXdhaXQgbW9kZWwuZ2V0X2ltYWdlX2VtYmVkZGluZ3MoaW1hZ2VJbnB1dHMpOwogIHNldFN0YXR1cygnSW1hZ2UgZW5jb2RlZC4gQ2xpY2sgdGhlIG9iamVjdDsgY2xpY2sgYWdhaW4gdG8gcmVmaW5lLicpOwp9Cgpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndXNlU2FtcGxlJykub25jbGljayA9ICgpID0+IGxvYWRJbWFnZUZyb21VUkwoU0FNUExFX1VSTCkuY2F0Y2goZSA9PiBzZXRTdGF0dXMoJycgKyBlKSk7CmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmaWxlJykub25jaGFuZ2UgPSAoZSkgPT4gewogIGNvbnN0IGYgPSBlLnRhcmdldC5maWxlc1swXTsKICBpZiAoZikgbG9hZEltYWdlRnJvbVVSTChVUkwuY3JlYXRlT2JqZWN0VVJMKGYpKS5jYXRjaChlcnIgPT4gc2V0U3RhdHVzKCcnICsgZXJyKSk7Cn07CmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdjbGVhcicpLm9uY2xpY2sgPSAoKSA9PiB7IGNsaWNrcyA9IFtdOyBsYXN0TWFzayA9IG51bGw7IGdlbkJ0bi5kaXNhYmxlZCA9IHRydWU7IHJlZHJhdygpOyBzZXRTdGF0dXMoJ0NsZWFyZWQuIENsaWNrIHRoZSBvYmplY3QuJyk7IH07CgovLyAtLS0tIGNsaWNrIGhhbmRsaW5nIC0tLS0KY2FudmFzLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgYXN5bmMgKGUpID0+IHsKICBpZiAoIWltYWdlRW1iZWRkaW5ncykgeyBzZXRTdGF0dXMoJ0xvYWQgYW4gaW1hZ2UgZmlyc3QuJyk7IHJldHVybjsgfQogIGNvbnN0IHJlY3QgPSBjYW52YXMuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCk7CiAgY29uc3QgeCA9IChlLmNsaWVudFggLSByZWN0LmxlZnQpIC8gcmVjdC53aWR0aCAqIGNhbnZhcy53aWR0aDsKICBjb25zdCB5ID0gKGUuY2xpZW50WSAtIHJlY3QudG9wKSAvIHJlY3QuaGVpZ2h0ICogY2FudmFzLmhlaWdodDsKICBjb25zdCBsYWJlbCA9IHBhcnNlSW50KGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ2lucHV0W25hbWU9bW9kZV06Y2hlY2tlZCcpLnZhbHVlLCAxMCk7CiAgY2xpY2tzLnB1c2goeyB4LCB5LCBsYWJlbCB9KTsKICBhd2FpdCBkZWNvZGUoKTsKfSk7Cgphc3luYyBmdW5jdGlvbiBkZWNvZGUoKSB7CiAgc2V0U3RhdHVzKCdTZWdtZW50aW5n4oCmJyk7CiAgY29uc3QgcmVzaGFwZWQgPSBpbWFnZUlucHV0cy5yZXNoYXBlZF9pbnB1dF9zaXplc1swXTsgLy8gW2gsIHddCiAgY29uc3QgcHRzID0gY2xpY2tzLm1hcChjID0+IFtjLnggLyBjYW52YXMud2lkdGggKiByZXNoYXBlZFsxXSwgYy55IC8gY2FudmFzLmhlaWdodCAqIHJlc2hhcGVkWzBdXSk7CiAgY29uc3QgbGJscyA9IGNsaWNrcy5tYXAoYyA9PiBCaWdJbnQoYy5sYWJlbCkpOwogIGNvbnN0IGlucHV0X3BvaW50cyA9IG5ldyBUZW5zb3IoJ2Zsb2F0MzInLCBwdHMuZmxhdChJbmZpbml0eSksIFsxLCAxLCBwdHMubGVuZ3RoLCAyXSk7CiAgY29uc3QgaW5wdXRfbGFiZWxzID0gbmV3IFRlbnNvcignaW50NjQnLCBsYmxzLCBbMSwgMSwgbGJscy5sZW5ndGhdKTsKCiAgY29uc3QgeyBwcmVkX21hc2tzLCBpb3Vfc2NvcmVzIH0gPSBhd2FpdCBtb2RlbCh7IC4uLmltYWdlRW1iZWRkaW5ncywgaW5wdXRfcG9pbnRzLCBpbnB1dF9sYWJlbHMgfSk7CiAgY29uc3QgbWFza3MgPSBhd2FpdCBwcm9jZXNzb3IucG9zdF9wcm9jZXNzX21hc2tzKHByZWRfbWFza3MsIGltYWdlSW5wdXRzLm9yaWdpbmFsX3NpemVzLCBpbWFnZUlucHV0cy5yZXNoYXBlZF9pbnB1dF9zaXplcyk7CiAgY29uc3QgbWFza1RlbnNvciA9IG1hc2tzWzBdWzBdOyAgICAgICAgICAgLy8gW251bV9tYXNrcywgSCwgV10KICBjb25zdCBbbnVtLCBILCBXXSA9IG1hc2tUZW5zb3IuZGltczsKICBjb25zdCBzY29yZXMgPSBpb3Vfc2NvcmVzLmRhdGE7CiAgbGV0IGJlc3QgPSAwOyBmb3IgKGxldCBpID0gMTsgaSA8IG51bTsgaSsrKSBpZiAoc2NvcmVzW2ldID4gc2NvcmVzW2Jlc3RdKSBiZXN0ID0gaTsKCiAgY29uc3QgbWQgPSBtYXNrVGVuc29yLmRhdGE7ICAgICAgICAgICAgICAgLy8gbGVuZ3RoIG51bSpIKlcgKDAvMSkKICBjb25zdCBvdXQgPSBuZXcgVWludDhBcnJheShIICogVyk7CiAgY29uc3Qgb2ZmID0gYmVzdCAqIEggKiBXOwogIGZvciAobGV0IGkgPSAwOyBpIDwgSCAqIFc7IGkrKykgb3V0W2ldID0gbWRbb2ZmICsgaV0gPyAyNTUgOiAwOwogIGxhc3RNYXNrID0geyBkYXRhOiBvdXQsIHdpZHRoOiBXLCBoZWlnaHQ6IEggfTsKICBnZW5CdG4uZGlzYWJsZWQgPSBmYWxzZTsKICByZWRyYXcoKTsKICBzZXRTdGF0dXMoYE1hc2sgcmVhZHkgKCR7Y2xpY2tzLmxlbmd0aH0gcG9pbnQke2NsaWNrcy5sZW5ndGggPiAxID8gJ3MnIDogJyd9KS4gUmVmaW5lIHdpdGggbW9yZSBjbGlja3MsIG9yIEdlbmVyYXRlIDNELmApOwp9CgpmdW5jdGlvbiByZWRyYXcoKSB7CiAgLy8gYmFzZSBpbWFnZQogIGlmIChpbWFnZVJhdyAmJiBpbWFnZVJhdy50b0NhbnZhcykgY3R4LmRyYXdJbWFnZShpbWFnZVJhdy50b0NhbnZhcygpLCAwLCAwKTsKICBpZiAobGFzdE1hc2spIHsKICAgIGNvbnN0IGltZyA9IGN0eC5nZXRJbWFnZURhdGEoMCwgMCwgY2FudmFzLndpZHRoLCBjYW52YXMuaGVpZ2h0KTsKICAgIGNvbnN0IGQgPSBpbWcuZGF0YTsKICAgIGZvciAobGV0IGkgPSAwOyBpIDwgbGFzdE1hc2suZGF0YS5sZW5ndGg7IGkrKykgewogICAgICBpZiAobGFzdE1hc2suZGF0YVtpXSkgewogICAgICAgIGRbaSAqIDRdID0gTWF0aC5yb3VuZChkW2kgKiA0XSAqIDAuNSk7CiAgICAgICAgZFtpICogNCArIDFdID0gTWF0aC5yb3VuZChkW2kgKiA0ICsgMV0gKiAwLjUgKyAxMDApOwogICAgICAgIGRbaSAqIDQgKyAyXSA9IE1hdGgucm91bmQoZFtpICogNCArIDJdICogMC41ICsgMTI4KTsKICAgICAgfQogICAgfQogICAgY3R4LnB1dEltYWdlRGF0YShpbWcsIDAsIDApOwogIH0KICBmb3IgKGNvbnN0IGMgb2YgY2xpY2tzKSB7CiAgICBjdHguYmVnaW5QYXRoKCk7IGN0eC5hcmMoYy54LCBjLnksIDcsIDAsIE1hdGguUEkgKiAyKTsKICAgIGN0eC5maWxsU3R5bGUgPSBjLmxhYmVsID8gJyMwMGUwMDAnIDogJyNmZjI4MjgnOwogICAgY3R4LmZpbGwoKTsgY3R4LmxpbmVXaWR0aCA9IDI7IGN0eC5zdHJva2VTdHlsZSA9ICcjZmZmJzsgY3R4LnN0cm9rZSgpOwogIH0KfQoKLy8gLS0tLSBnZW5lcmF0ZSAzRCB2aWEgdGhlIEZsYXNrIHByb3h5IC0+IFNhZ2VNYWtlciAtLS0tCmZ1bmN0aW9uIGNhbnZhc1RvQjY0KGMpIHsgcmV0dXJuIGMudG9EYXRhVVJMKCdpbWFnZS9wbmcnKS5zcGxpdCgnLCcpWzFdOyB9CgpmdW5jdGlvbiBpbWFnZUI2NCgpIHsKICBjb25zdCBjID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnY2FudmFzJyk7IGMud2lkdGggPSBjYW52YXMud2lkdGg7IGMuaGVpZ2h0ID0gY2FudmFzLmhlaWdodDsKICBjLmdldENvbnRleHQoJzJkJykuZHJhd0ltYWdlKGltYWdlUmF3LnRvQ2FudmFzKCksIDAsIDApOwogIHJldHVybiBjYW52YXNUb0I2NChjKTsKfQpmdW5jdGlvbiBtYXNrQjY0KCkgewogIGNvbnN0IGMgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdjYW52YXMnKTsgYy53aWR0aCA9IGxhc3RNYXNrLndpZHRoOyBjLmhlaWdodCA9IGxhc3RNYXNrLmhlaWdodDsKICBjb25zdCBjeCA9IGMuZ2V0Q29udGV4dCgnMmQnKTsgY29uc3QgaWQgPSBjeC5jcmVhdGVJbWFnZURhdGEoYy53aWR0aCwgYy5oZWlnaHQpOwogIGZvciAobGV0IGkgPSAwOyBpIDwgbGFzdE1hc2suZGF0YS5sZW5ndGg7IGkrKykgeyBjb25zdCB2ID0gbGFzdE1hc2suZGF0YVtpXTsgaWQuZGF0YVtpKjRdPXY7IGlkLmRhdGFbaSo0KzFdPXY7IGlkLmRhdGFbaSo0KzJdPXY7IGlkLmRhdGFbaSo0KzNdPTI1NTsgfQogIGN4LnB1dEltYWdlRGF0YShpZCwgMCwgMCk7CiAgcmV0dXJuIGNhbnZhc1RvQjY0KGMpOwp9Cgpjb25zdCBzbGVlcCA9IChtcykgPT4gbmV3IFByb21pc2UociA9PiBzZXRUaW1lb3V0KHIsIG1zKSk7CgpnZW5CdG4ub25jbGljayA9IGFzeW5jICgpID0+IHsKICBpZiAoIWxhc3RNYXNrKSByZXR1cm47CiAgZ2VuQnRuLmRpc2FibGVkID0gdHJ1ZTsKICBzdGF0dXMzZEVsLnRleHRDb250ZW50ID0gJ1N1Ym1pdHRpbmcgdG8gdGhlIFNhZ2VNYWtlciBlbmRwb2ludOKApic7CiAgY29uc3QgdDAgPSBwZXJmb3JtYW5jZS5ub3coKTsKICB0cnkgewogICAgLy8gU3RhcnQgdGhlIGpvYiAocmV0dXJucyBpbW1lZGlhdGVseSB3aXRoIGEgam9iIGlkKSDigJQgYXZvaWRzIHRoZSB0dW5uZWwncwogICAgLy8gfjYwcyByZXF1ZXN0IHRpbWVvdXQgdGhhdCBsb25nLWhlbGQgcmVxdWVzdHMgaGl0ICg1MDQpLgogICAgY29uc3Qgc3RhcnRSZXNwID0gYXdhaXQgZmV0Y2gobmV3IFVSTCgnZ2VuZXJhdGUnLCBkb2N1bWVudC5iYXNlVVJJKSwgewogICAgICBtZXRob2Q6ICdQT1NUJywgaGVhZGVyczogeyAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nIH0sCiAgICAgIGJvZHk6IEpTT04uc3RyaW5naWZ5KHsgaW1hZ2U6IGltYWdlQjY0KCksIG1hc2s6IG1hc2tCNjQoKSwgc2VlZDogcGFyc2VJbnQoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3NlZWQnKS52YWx1ZSB8fCAnNDInLCAxMCkgfSksCiAgICB9KTsKICAgIGlmICghc3RhcnRSZXNwLm9rKSB0aHJvdyBuZXcgRXJyb3IoJ3NlcnZlciAnICsgc3RhcnRSZXNwLnN0YXR1cyArICc6ICcgKyAoYXdhaXQgc3RhcnRSZXNwLnRleHQoKSkpOwogICAgY29uc3QgeyBqb2JfaWQgfSA9IGF3YWl0IHN0YXJ0UmVzcC5qc29uKCk7CgogICAgLy8gUG9sbCBmb3IgdGhlIHJlc3VsdCAoc2hvcnQgcmVxdWVzdHM7IHR1bm5lbC1zYWZlKS4KICAgIGxldCByID0gbnVsbDsKICAgIGNvbnN0IGRlYWRsaW5lID0gRGF0ZS5ub3coKSArIDIwICogNjAgKiAxMDAwOwogICAgd2hpbGUgKERhdGUubm93KCkgPCBkZWFkbGluZSkgewogICAgICBhd2FpdCBzbGVlcCgzMDAwKTsKICAgICAgY29uc3QgcHUgPSBuZXcgVVJMKCdwb2xsJywgZG9jdW1lbnQuYmFzZVVSSSk7IHB1LnNlYXJjaFBhcmFtcy5zZXQoJ2lkJywgam9iX2lkKTsKICAgICAgY29uc3QgcHIgPSBhd2FpdCBmZXRjaChwdSk7CiAgICAgIGlmICghcHIub2spIHsgc3RhdHVzM2RFbC50ZXh0Q29udGVudCA9ICdwb2xsICcgKyBwci5zdGF0dXMgKyAn4oCmIHJldHJ5aW5nJzsgY29udGludWU7IH0KICAgICAgY29uc3QgaiA9IGF3YWl0IHByLmpzb24oKTsKICAgICAgaWYgKGouc3RhdHVzID09PSAnZG9uZScpIHsgciA9IGo7IGJyZWFrOyB9CiAgICAgIGlmIChqLnN0YXR1cyA9PT0gJ2Vycm9yJykgdGhyb3cgbmV3IEVycm9yKGouZXJyb3IgfHwgJ2VuZHBvaW50IGVycm9yJyk7CiAgICAgIHN0YXR1czNkRWwudGV4dENvbnRlbnQgPSBgV29ya2luZyBvbiB0aGUgR1BV4oCmICR7TWF0aC5yb3VuZCgocGVyZm9ybWFuY2Uubm93KCkgLSB0MCkgLyAxMDAwKX1zIChmaXJzdCBydW4gYWxzbyBsb2FkcyB0aGUgbW9kZWwpYDsKICAgIH0KICAgIGlmICghcikgdGhyb3cgbmV3IEVycm9yKCd0aW1lZCBvdXQgYWZ0ZXIgMjAgbWluJyk7CgogICAgY29uc3QgdG90YWwgPSAoKHBlcmZvcm1hbmNlLm5vdygpIC0gdDApIC8gMTAwMCkudG9GaXhlZCgwKTsKICAgIGNvbnN0IGJ5dGVzID0gVWludDhBcnJheS5mcm9tKGF0b2Ioci5wbHlfYjY0KSwgYyA9PiBjLmNoYXJDb2RlQXQoMCkpOwogICAgY29uc3QgYmxvYiA9IG5ldyBCbG9iKFtieXRlc10sIHsgdHlwZTogJ2FwcGxpY2F0aW9uL29jdGV0LXN0cmVhbScgfSk7CiAgICBjb25zdCB1cmwgPSBVUkwuY3JlYXRlT2JqZWN0VVJMKGJsb2IpOwogICAgY29uc3QgZGwgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZGwnKTsgZGwuaHJlZiA9IHVybDsgZGwuZG93bmxvYWQgPSAncmVjb25zdHJ1Y3Rpb24ucGx5JzsgZGwuc3R5bGUuZGlzcGxheSA9ICdpbmxpbmUnOwogICAgY29uc3QgcmVjb24gPSByLnRpbWluZ19zICYmIHIudGltaW5nX3MucmVjb25zdHJ1Y3Q7CiAgICBzdGF0dXMzZEVsLnRleHRDb250ZW50ID0gYCR7KHIubnVtX2dhdXNzaWFuc3x8MCkudG9Mb2NhbGVTdHJpbmcoKX0gZ2F1c3NpYW5zIMK3ICR7cmVjb24/KCdHUFUgJytyZWNvbisncyDCtyAnKTonJ310b3RhbCAke3RvdGFsfXNgOwogICAgYXdhaXQgc2hvd1NwbGF0KHVybCk7CiAgfSBjYXRjaCAoZSkgewogICAgc3RhdHVzM2RFbC50ZXh0Q29udGVudCA9ICdHZW5lcmF0aW9uIGZhaWxlZDogJyArIGU7CiAgfSBmaW5hbGx5IHsKICAgIGdlbkJ0bi5kaXNhYmxlZCA9IGZhbHNlOwogIH0KfTsKCi8vIC0tLS0gaW50ZXJhY3RpdmUgM0QgR2F1c3NpYW4tc3BsYXQgdmlld2VyIChvcmJpdCB3aXRoIG1vdXNlKSAtLS0tCmxldCB2aWV3ZXIgPSBudWxsOwphc3luYyBmdW5jdGlvbiBzaG93U3BsYXQodXJsKSB7CiAgdHJ5IHsKICAgIGNvbnN0IEdTID0gYXdhaXQgaW1wb3J0KCdodHRwczovL2VzbS5zaC9AbWtrZWxsb2dnL2dhdXNzaWFuLXNwbGF0cy0zZEAwLjQuNz9idW5kbGUnKTsKICAgIGlmICh2aWV3ZXIpIHsgdHJ5IHsgYXdhaXQgdmlld2VyLmRpc3Bvc2UoKTsgfSBjYXRjaCAoXykge30gdmlld2VyID0gbnVsbDsgfQogICAgY29uc3Qgcm9vdCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd2aWV3ZXInKTsgcm9vdC5pbm5lckhUTUwgPSAnJzsKICAgIHZpZXdlciA9IG5ldyBHUy5WaWV3ZXIoewogICAgICByb290RWxlbWVudDogcm9vdCwKICAgICAgc2hhcmVkTWVtb3J5Rm9yV29ya2VyczogZmFsc2UsICAgLy8gYXZvaWRzIENPT1AvQ09FUCBoZWFkZXIgcmVxdWlyZW1lbnRzCiAgICAgIGR5bmFtaWNTY2VuZTogZmFsc2UsCiAgICAgIHVzZUJ1aWx0SW5Db250cm9sczogdHJ1ZSwgICAgICAgIC8vIE9yYml0Q29udHJvbHM6IGRyYWcgdG8gcm90YXRlLCBzY3JvbGwgdG8gem9vbQogICAgICBjYW1lcmFVcDogWzAsIDEsIDBdLAogICAgfSk7CiAgICBhd2FpdCB2aWV3ZXIuYWRkU3BsYXRTY2VuZSh1cmwsIHsgZm9ybWF0OiBHUy5TY2VuZUZvcm1hdC5QbHksIHNob3dMb2FkaW5nVUk6IGZhbHNlIH0pOwogICAgdmlld2VyLnN0YXJ0KCk7CiAgfSBjYXRjaCAoZSkgewogICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3N0YXR1czNkJykudGV4dENvbnRlbnQgPQogICAgICAnSW4tcGFnZSB2aWV3ZXIgZmFpbGVkICgnICsgZSArICcpLiBVc2UgdGhlIERvd25sb2FkIC5wbHkgbGluayBhbmQgb3BlbiBpdCBhdCBodHRwczovL3N1cGVyc3BsLmF0L2VkaXRvcic7CiAgfQp9Cjwvc2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K"
_invoke = None
_JOBS = {}  # job_id -> {"status": "pending"|"done"|"error", ...}
import threading as _threading
import uuid as _uuid


def _get_invoke():
    global _invoke
    if _invoke is None:
        _invoke = _default_invoke_factory()
    return _invoke


async def _page(request):
    import base64 as _b64
    return HTMLResponse(_b64.b64decode(_INDEX_HTML_B64).decode("utf-8"))


def _run_job(job_id, payload):
    try:
        result = _get_invoke()(payload)
        if "ply_b64" in result:
            result["status"] = "done"
            _JOBS[job_id] = result
        else:
            _JOBS[job_id] = {"status": "error", "error": f"endpoint returned no model: {result}"}
    except Exception as exc:
        _JOBS[job_id] = {"status": "error", "error": str(exc)}


async def _generate(request):
    # Start the job in the background and return a job id immediately. Holding one
    # long request open (1-2 min reconstruction) trips the gradio.live tunnel's
    # ~60s timeout -> 504. The browser polls /poll instead (short requests).
    try:
        data = await request.json()
    except Exception as exc:
        return JSONResponse({"error": f"bad JSON: {exc}"}, status_code=400)
    if not data.get("image") or not data.get("mask"):
        return JSONResponse({"error": "image and mask are required"}, status_code=400)
    payload = {
        "image": data["image"],
        "mask": data["mask"],
        "seed": int(data.get("seed", 42)),
        "render_preview": False,
    }
    job_id = _uuid.uuid4().hex
    _JOBS[job_id] = {"status": "pending"}
    _threading.Thread(target=_run_job, args=(job_id, payload), daemon=True).start()
    return JSONResponse({"job_id": job_id})


async def _poll(request):
    job_id = request.query_params.get("id")
    job = _JOBS.get(job_id)
    if job is None:
        return JSONResponse({"status": "error", "error": "unknown job id"}, status_code=404)
    return JSONResponse(job)


def main():
    with gr.Blocks() as demo:
        gr.Markdown("### SAM 3D Objects (WebGPU)\nThe app is served at **`/app`** on this same URL — open the `…gradio.live/app` link printed in the terminal.")

    demo.launch(share=True, prevent_thread_lock=True)

    # Attach our routes to Gradio's FastAPI server AT THE FRONT so they take
    # priority over Gradio's catch-all SPA route. The share tunnel forwards them.
    demo.app.router.routes.insert(0, Route("/app", _page, methods=["GET"]))
    demo.app.router.routes.insert(0, Route("/generate", _generate, methods=["POST"]))
    demo.app.router.routes.insert(0, Route("/poll", _poll, methods=["GET"]))

    share = getattr(demo, "share_url", None)
    print("\n" + "=" * 70)
    print("OPEN THIS IN YOUR BROWSER (note the /app suffix):")
    print(f"   {share}/app" if share else "   <share url not ready — check above>")
    print("=" * 70 + "\n")

    try:
        demo.block_thread()  # keep the server alive (Ctrl-C to stop)
    except (AttributeError, KeyboardInterrupt):
        import time
        try:
            while True:
                time.sleep(3600)
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
